# Generated by Django 4.2.30 on 2026-04-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='service_photos/', verbose_name='Фото акта')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Акт выполненных работ',
                'verbose_name_plural': 'Акты выполненных работ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WashReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='wash_photos/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Отчёт о мойке',
                'verbose_name_plural': 'Отчёты о мойке',
                'ordering': ['-created_at'],
            },
        ),
    ]
