# Generated by Django 4.2.30 on 2026-04-23 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='washreport',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wash_reports', to='vehicles.vehicle', verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reports', to='vehicles.vehicle', verbose_name='Автомобиль'),
        ),
    ]
