# Generated by Django 4.2.30 on 2026-04-27 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MileageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(verbose_name='Пробег (км)')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mileage_photos/', verbose_name='Фото одометра')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mileage_reports', to='vehicles.vehicle', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Отчёт о пробеге',
                'verbose_name_plural': 'Отчёты о пробеге',
                'ordering': ['-created_at'],
            },
        ),
    ]
